/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleDexSol from "./SimpleDEX.sol";
export type { simpleDexSol };
export type { MockPepe } from "./MockPepe";
export type { MockUSDC } from "./MockUSDC";
