/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as simpleDexSol from "./SimpleDEX.sol";
export { MockPepe__factory } from "./MockPepe__factory";
export { MockUSDC__factory } from "./MockUSDC__factory";
